fix: EC2_INSTANCE의 유효성을 확인한다.

diff --git a/.github/workflows/prod-cd-pipeline.yml b/.github/workflows/prod-cd-pipeline.yml
--- a/.github/workflows/prod-cd-pipeline.yml
+++ b/.github/workflows/prod-cd-pipeline.yml
@@ -60,7 +60,6 @@ jobs:
       # Step 6: .env.prod 파일 생성
       - name: .env.prod 파일 생성
         run: |
-          echo "Step 6: .env.prod 파일 생성 시작"
           echo "PROJECT_NAME=${{env.PROJECT_NAME}}" > .env.prod
           echo "MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }}" >> .env.prod
           echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env.prod
@@ -70,7 +69,6 @@ jobs:
           echo "GMAIL_USERNAME=${{ secrets.GMAIL_USERNAME }}" >> .env.prod
           echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> .env.prod
           echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env.prod
-          echo "Step 6: .env.prod 파일 생성 완료"
 
       # Step 7: .env.prod 파일 아티팩트 업로드
       - name: .env.prod 파일 아티팩트 업로드
@@ -82,44 +80,34 @@ jobs:
       # Step 8: Docker Compose를 사용하여 Docker 이미지 빌드
       - name: Docker 이미지 빌드
         run: |
-          echo "Step 8: Docker Compose를 사용하여 Docker 이미지 빌드 시작"
           docker-compose -f prod-build-compose.yml --env-file .env.prod build
-          echo "Step 8: Docker Compose를 사용하여 Docker 이미지 빌드 완료"
-          echo "Built Docker images:"
           docker images
 
       # Step 9: Docker 이미지 태그 및 ECR에 푸시
       - name: Docker 이미지 태그 및 ECR에 푸시
         run: |
-          echo "Step 9: Docker 이미지 태그 및 ECR에 푸시 시작"
-          echo "PROJECT_NAME: ${PROJECT_NAME}"
-          echo "ECR_URI: ${ECR_URI}"
-          echo "ECR_NAME: ${ECR_NAME}"
-          
-          echo "ECR 로그인 시도 중..."
-          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_URI}
-          if [ $? -ne 0 ]; then
-            echo "ECR 로그인 실패"
-            exit 1
-          fi
-          
-          echo "Docker 이미지 태그 중..."
           docker tag ${PROJECT_NAME}:latest ${ECR_URI}/${ECR_NAME}:latest
-          if [ $? -ne 0 ]; then
-            echo "Docker 이미지 태그 실패"
-            exit 1
-          fi
-          
-          echo "Docker 이미지 ECR로 푸시 중..."
           docker push ${ECR_URI}/${ECR_NAME}:latest
-          if [ $? -ne 0 ]; then
-            echo "Docker 이미지 푸시 실패"
+
+      # Step 10: EC2 인스턴스 상태 확인 및 시작
+      - name: EC2 인스턴스 상태 확인 및 시작
+        run: |
+          set -e
+          INSTANCE_STATE=$(aws ec2 describe-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }} --query "Reservations[].Instances[].State.Name" --output text)
+          if [ -z "$INSTANCE_STATE" ]; then
+            echo "Invalid instance ID or instance does not exist"
             exit 1
           fi
-          
-          echo "Step 9: Docker 이미지 태그 및 ECR에 푸시 완료"
+          echo "Current instance state: $INSTANCE_STATE"
+          if [ "$INSTANCE_STATE" != "running" ]; then
+            echo "Starting instance..."
+            aws ec2 start-instances --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
+            aws ec2 wait instance-running --instance-ids ${{ secrets.EC2_INSTANCE_ID }}
+          else
+            echo "Instance is already running."
+          fi
 
-      # Step 10: 파일을 EC2로 전송하고 배포 준비
+      # Step 11: 파일을 EC2로 전송하고 배포 준비
       - name: EC2에 파일 전송 및 배포 준비
         run: |
           aws ssm send-command \
@@ -135,7 +123,7 @@ jobs:
             --max-concurrency "50" \
             --max-errors "0"
 
-      # Step 11: EC2에서 Docker Compose를 사용하여 배포
+      # Step 12: EC2에서 Docker Compose를 사용하여 배포
       - name: EC2에서 Docker Compose로 배포
         run: |
           aws ssm send-command \
